# Generated by Django 4.1.13 on 2024-05-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
