# Generated by Django 4.1.13 on 2024-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='profile',
            name='task',
            field=models.CharField(default='none', max_length=225),
        ),
    ]
