# Generated by Django 4.1.13 on 2024-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_delete_todo_profile_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='task',
        ),
    ]
