# Generated by Django 4.1.13 on 2024-05-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_todo_remove_profile_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='task',
        ),
    ]
